version: "3.9"

services:
  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/go/src/home
    command: "bash -c 'sh build.sh'"
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Tokyo
  db:
    build:
      context: ./docker
      dockerfile: mysql.Dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    platform: linux/x86_64
    volumes:
      - /var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=home
  frontend:
    build:
      context: ./docker
      dockerfile: frontend.Dockerfile
    volumes:
      - ./frontend/:/app/
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
  mock-api:
    image: stoplight/prism
    container_name: "mock-api"
    ports:
      - "0.0.0.0:4010:4010"
    platform: linux/amd64
    command: mock -h 0.0.0.0 /swagger.yaml
    volumes:
      - ./backend/docs/swagger.yaml:/swagger.yaml
